### ISSUE TITLE
path guided linear 1D SGD sorting

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#100]
The linear 1D SGD sorting in `odgi sort` precalculates all pairwise node distances, so called terms. This means we have a quadratic memory usage. Having large graphs with billions of nodes, this won't scale. 
Also, randomly picking nodes from a normal distribution for the current iteration might not be the ideal way. @ekg Proposed to draw the second node from a Zipfian distribution. Or we can try out any other distribution.

- We need to replace the `const PathHandleGraph& graph` input at https://github.com/vgteam/odgi/blob/39f467afa173d64e03eae85d27d818150eeb8ce1/src/algorithms/linear_sgd.cpp#L6 with the path index implemented in https://github.com/vgteam/odgi/blob/master/src/algorithms/xp.cpp.
This means functions like `index.for_each_handle` will have to be rewritten in `xp`.
- We need to calculate each term on the fly. Here the first node will be picked via normal distribution and the second node via Zipfian distribution. We should also try to hit the same path again maybe? Here a lot of tweaks and variations are possible.
- How can we sort graphs with no paths? For each disconnected graph, we need to find a random way to generate paths.

**Comment by subwaystation** [comment]
Code which can directly be ported into `odgi`: https://stackoverflow.com/questions/9983239/how-to-generate-zipf-distributed-numbers-efficiently

**Comment by subwaystation** [comment]
Some feedback from @tpook92: The best sort would be to draw as few links as possible. 
During sorting: Cases, where direct successors are available, should be favored.

**Comment by subwaystation** [comment]
Some more questions to think about that popped up in my mind:

- Does sorting a graph influence `vg deconstruct` or `VGpop`? Would we get different results there? Would that be a problem?
- Do we need sort methods that reverse the just applied sorting? I can't think of a case we might need that, but I came through my mind.

**Comment by josiahseaman** [comment]
@subwaystation @ekg I feel like I need to play the part of the court jester here and ask the stupid questions.  In the use case of SAR-CoV-2 where we have a mostly homogenous, linear pangenome, what's the problem with this dummy sort algorithm?

### Dummy Linear Sort
```
ordering = []
for each path:
     prev_index = 0
     for node, x in enumerate(path):
          if node not in ordering:
               ordering.insert(node, prev_index +1) // insert at x
          prev_index = ordering.indexOf(node)
```
You can use a linked list or equiv to make inserts constant time.  The reason I ask is that sorting is our blocking problem before release.

**Comment by subwaystation** [comment]
Hi @josiahseaman Thanks for the feedback. For the path guided linear 1D SGD sort I will implement an option where one can specify the paths and therefore chromosomes to use as a `reference guide` during the sort. This should achieve what you want to have.

**Comment by ekg** [comment]
This is getting very close to completion! Nice!

**Comment by subwaystation** [comment]
This is done. See `odgi sort`.
