### ISSUE TITLE
please include Buildable Source Tarballs in the releases

### ISSUE THREAD

**Issue by mr-c** [vgteam/odgi#109]
That is, with the entire contents of `deps/` with all git-submodules checked out

Thanks!

**Comment by subwaystation** [comment]
Odgi is present in Bioconda https://bioconda.github.io/recipes/odgi/README.html.
Would that help you, too?

**Comment by mr-c** [comment]
I'm preparing the odgi package for Debian

**Comment by subwaystation** [comment]
Cool. If you still need such a kind of release I can only point to @ekg. Please mail back, if so.

**Comment by mr-c** [comment]
Yes, I still need the full source tarballs here

**Comment by subwaystation** [comment]
@mr-c I am creating asciidocs and manpages at https://github.com/vgteam/odgi/tree/docs/docs/asciidocs for `odgi` and each subcommand. Do you have any special requirement to link the manpages to the specified subcommand in the Debian package?

**Comment by mr-c** [comment]
@subwaystation Great! Either install the generated manual pages along with the other outputs, or we can pick them out of the build tree. Here's a reminder how sub commands work: https://stackoverflow.com/a/32750157

**Comment by subwaystation** [comment]
Thanks for that link! Luckily, I already formatted the names of the manpages correctly, so you can pick them up in the tree and copy them to the appropriate folder.

**Comment by subwaystation** [comment]
Hi @mr-c 
Could you please check out the new release? Thanks!

**Comment by mr-c** [comment]
Hello @subwaystation 
https://github.com/vgteam/odgi/archive/v0.5.tar.gz is autogenerated by GitHub, so therefore it does not contain any of the git submodule directories like https://github.com/vgteam/odgi/tree/master/deps 

You'll need to make a separate tarball (preferably something automated, so it is reproducible) and attach it to the release. Please use a consistent naming convention.

For an example see https://github.com/vgteam/vg/releases/tag/v1.29.0 ; they named their tarball `vg-v1.29.0.tar.gz`, for odgi I would recommend `odgi-v0.5.tar.gz` or with xz compression: `odgi-v0.5.tar.xz`

Thanks!

**Comment by AndreaGuarracino** [comment]
Hi @mr-c,

is this what you need for a proper release?

https://github.com/vgteam/odgi/releases/download/v0.5.1/odgi-v0.5.1.tar.gz

**Comment by mr-c** [comment]
@AndreaGuarracino That works, thank you!
