### ISSUE TITLE
Bioconda Bump

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#112]
Hi @dpryan79,

it seems the autobump of Bioconda still does not work? The current release of odgi is 0.4.1 but I am seeing [0.3](https://bioconda.github.io/recipes/odgi/README.html?highlight=odgi).
Could you please trigger a Bioconda build? Thanks!

**Comment by dpryan79** [comment]
My guess is that this is due to using a git tag rather than a regular release tar ball. Can you just make a regular PR to update the recipe and ideally use the release tarball for building?

**Comment by subwaystation** [comment]
So a source tarball release as proposed in https://github.com/vgteam/odgi/issues/109 and an adjustment of the Bioconda recipe should take care of it?

**Comment by dpryan79** [comment]
Yup that should do it.

**Comment by subwaystation** [comment]
@dpryan79 Could you please take a look again? We made a new release. Thanks ;)

**Comment by dpryan79** [comment]
Not sure why the bot didn't pick it up. Can you create an update PR manually?
