### ISSUE TITLE
Non-contiguous node IDs for purging junk data

### ISSUE THREAD

**Issue by josiahseaman** [vgteam/odgi#118]
In our SARS-CoV-2 use case, we have found a small number of individuals with >10kbp private insertions.  We'd like to generate a list of these and exclude them from later steps.  Currently, this involves excluding them from seqwish and regenerating everything: seqwish -> odgi sort -> odgi bin -> component_segmentation.  It's taking around 5 hours roundtrip.

Would it be possible to output from odgi a sorted GFA file?  From here we could use regex / programs to delete content but leave the same sort order.  This would mean node ids would not be contiguous, but bin ids would be, because we'd re-run odgi bin and downstream.  This is likely related to #30 where it sounds like non-contiguous node ids are tolerated, but slow.

**Comment by ekg** [comment]
What is taking so long in that pipeline? The seqwish/odgi components should only take a few minutes. Why don't you detect the paths with very large non-matching segments there, before segmentation?

For GFA output, do you mean odgi view? The output of that is exactly equivalent to the graph. 

Compacting without sorting is supported in the API. I'm not sure if it's exposed directly by a given command. I'll look.

**Comment by ekg** [comment]
There is a python API in odgi that you can use to work on the graph directly. Why don't you code up the filter you need using that?

**Comment by josiahseaman** [comment]
A closer review on Arvados shows that is was odgi2RDF that was taking four hours.  The only other significant step is overlapReads, which is minimap.  We'll look at editing out the pairwise comparisons containing excluded individuals.  Thanks for questioning why that was taking so long.  I hear GISAID has 25,000 SARS2 genomes now.  So we'll still have some scalability challenges to overcome.
