### ISSUE TITLE
path guided linear 1D SGD sort - edge cases

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#129]
The following graphs break the sorting algorithm because each path walks through exactly one node. We may have to address this at some point.
[DRB5-3127.gfa.txt](https://github.com/vgteam/odgi/files/4785270/DRB5-3127.gfa.txt)
[V-352962.gfa.txt](https://github.com/vgteam/odgi/files/4785271/V-352962.gfa.txt)

**Comment by subwaystation** [comment]
@ekg discovered this in #127 .

**Comment by josiahseaman** [comment]
How about a special case statement that tries to put the first node of a
path at the beginning when it does not share any nodes with the list of
sorted nodes?
