### ISSUE TITLE
Build fails with clang

### ISSUE THREAD

**Issue by jeizenga** [vgteam/odgi#13]
I tried to build this on a Mac with clang, but it won't complete. The build fails while compiling `bsort` with a complaint about the `-fopenmp` flag.

```
[ 25%] Performing build step for 'bsort'
[ 25%] Building CXX object CMakeFiles/bsort.dir/src/bsort.cpp.o
clang: error: unsupported option '-fopenmp'
make[5]: *** [CMakeFiles/bsort.dir/src/bsort.cpp.o] Error 1
make[4]: *** [CMakeFiles/bsort.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [bsort-prefix/src/bsort-stamp/bsort-build] Error 2
make[1]: *** [CMakeFiles/bsort.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ekg** [comment]
Yeah, this is a known problem. Unfortunately, I don't use a Mac, and there is no way to reproduce the build environment if you don't have one.

I've tried to implement a fix for this.

Would you please test the current git HEAD?

**Comment by ekg** [comment]
OK, I see your PR, and I've merged it in.

Does it work now? Can I close this issue?
