### ISSUE TITLE
'rdseed failed' error when using '-p Y' in odgi sort

### ISSUE THREAD

**Issue by jmonlong** [vgteam/odgi#137]
I got the following error when trying to sort a graph made with minimap2+seqwish:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device: rdseed failed
Aborted (core dumped)
```

Have you encountered this error before?

I was running the following pipe:

```
odgi build -g input.gfa -o - -p \
    | odgi chop -i - -o - -c 16 | odgi sort -t 4 -i - -o - -O \
    | odgi sort -t 4 -p Ygs -G 0.1 -i - -o - -P \
    | odgi view -i - -g > output.gfa
```

I narrowed the error down to the second sort: `odgi sort -t 4 -p Ygs -G 0.1 -i - -o - -P`. More specifically I only get the error when including `Y` in the `-p` pipeline parameter.

My input graph is in this vg-team s3 bucket for now at s3://vg-k8s/vgamb/chr20/seqwish/asm20-dropl10000-k256-l256/lc2019_12ont-hg38.seqwish.asm20-dropl10000-k256-l256.gfa.gz

**Comment by ekg** [comment]
This suggests to me that you weren't able to get random bits from the system random device.

I can change the seed to be the system time. That'd be fine for all practical use.

**Comment by ekg** [comment]
I've marked this as closed, but please check to confirm. I wasn't able to reproduce this problem. I think it's related to the system you're running on.

**Comment by jmonlong** [comment]
Thanks, it's working now. 

Yeah, maybe something is missing or wrong in my container. I couldn't find an easy fix when googling the error.

**Comment by AndreaGuarracino** [comment]
Hi @ekg, just to confirm that I just had the same problem with the yeast pangenomes from your repository, but updating odgi with your commit (b129147) has solved the problem.
