### ISSUE TITLE
/odgi/src/odgi.cpp:565: uint64_t odgi::graph_t::edge_delta_to_id(uint64_t, uint64_t) const: Assertion `delta != 0' failed

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/odgi#153]
This is coming when accessing a larger Odgi file through SpOdgi.

Sorry for the sparse details. I have no idea where this is comeing from.

**Comment by subwaystation** [comment]
The whole backing implementation of odgi's core model has changed. Closing this for now.
If it should come up again, please re-open. Thanks!
