### ISSUE TITLE
Can the graph_t handle paths with multiple occurrences of the same node?

### ISSUE THREAD

**Issue by jeizenga** [vgteam/odgi#18]
As far as I can tell, the implementation of a step is (node_id, path_id), correct? Won't this create a fundamental ambiguity if a path traverses a node multiple times (e.g. in a CNV)? I think it might be worth also spending some of the bits on the path_id portion to encode that the step is the n-th occurrence of that node on that path.

**Comment by ekg** [comment]
Yes, it can. The order of the crossing is stored implicitly in the backing
path step array and is pointed to by each step. This is a key feature of
the model. Maybe I forgot to add it to the step interface or it's not
clearly documented? I'll make sure this is fixed when I update to match the
new HandleGraph.

**Comment by ekg** [comment]
I've looked back at this. Let me clarify what's going on.

A step_t in odgi is an unpacked version of a given path step on a given node:

https://github.com/vgteam/odgi/blob/3c19e1154005af1e9dc0ea7e1fa0baf00ee791c3/src/node.hpp#L39

```cpp
struct step_t {
   uint64_t data[5] = { 0, 0, 0, 0, 0 }; // PATH_RECORD_LENGTH
   step_t(void) { }
   step_t(const uint64_t& id,
              const bool& rev,
              const uint64_t& prev_id,
              const uint64_t& prev_rank,
              const uint64_t& next_id,
              const uint64_t& next_rank) {
     data[0] = pack_step(id, rev);
     data[1] = prev_id;
     data[2] = prev_rank;
     data[3] = next_id;
     data[4] = next_rank;
}
```

Each step tells you where the previous and next path steps for that path are. They can be on any node, including the current one.

It does not itself contain the rank of the step on the node, but it is only possible to obtain a step if you have a step rank, so this is not necessary to add into it.

Given the design, it's trivial for paths to cross a given node multiple times. I hope this is all clear.
