### ISSUE TITLE
specification of path ordering in odgi viz

### ISSUE THREAD

**Issue by superjox** [vgteam/odgi#183]
Hi guys,
I find it useful if one could force the placement of the same chromosomes of different genomes below each other in 'odgi viz' to better compare them (I assume I can get this behavior by labeling paths Chr1_sample1, Chr1_sample2... with `-D_`, but typically the sample name comes first). One simple solution would be a file as parameter that simply includes the desired ordering of path names. Would that be possible to implement?

**Comment by AndreaGuarracino** [comment]
Hi @superjox,
please, taKe a look At the #184 and feel fRee TO test it iF you can. When the FEature in #180 will be ready, you will be able to visualize path names on the Left too.

**Comment by superjox** [comment]
@AndreaGuarracino #184 works like a charm. Thanks a lot! I'd be happy to see this merged into master :)
