### ISSUE TITLE
viz should represent relative orientation

### ISSUE THREAD

**Issue by ekg** [vgteam/odgi#32]
This is a pretty simple one. I need to come up with a visual motif that indicates which relative orientation a path has in a given region.

I think the only thing that is reliably available at all path rendering widths will be a lighter/darker color for the given path steps.

**Comment by MoinSebi** [comment]
Is this already implemented? I saw the -S and -A flag in the `odgi viz` command and was not able to recall what an "alignment-related visual motive" was.

**Comment by ekg** [comment]
Use odgi bin to get this and plot it in another program like R
