### ISSUE TITLE
Feature: Output Pangenome sequence

### ISSUE THREAD

**Issue by josiahseaman** [vgteam/odgi#49]
Would you be so kind as to modify ODGI bin at 1bp bins to output a pangenome sequence?  It'd be the concatenation of all node sequences in the order that you already sorted them.  A single long string.

```python
#Python pseudocode for pangenome matrix sequence
with open(bin_output_file, 'w') as out:
	out.write(regular_bin_output(my_sort_order))
	if bin_size == 1:
		out.write("'Pangenome Sequence':")
		pangenome = ''.join(node.seq for node in my_sort_order)
		out.write(pangenome)
```

This could potentially be triggered at every bin level or only bin_size = 1bp.  Sequence length with real data tend to be 120% the size of the starting genome, so 100s of MB, not 100s of GB.  Perhaps a command line flag? `--emit_sequence`

**Comment by ekg** [comment]
I think this should be the default behavior. I can make that so it ends up
in the bin output.
