### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#55]
Hi @ekg ,

following up the discussion at https://github.com/JervenBolleman/spodgi/issues/3, could you please make a release or pre-release of odgi?
Thanks!

Best,
Simon

**Comment by SilasK** [comment]
Could I also ask for a docker container

**Comment by subwaystation** [comment]
As soon as we have a release, we can bring it to Conda. Then a docker container will be straightforward.

**Comment by SilasK** [comment]
Conda is even better!

**Comment by SilasK** [comment]
@ekg maybe it's not the place to ask. 
How complicated would it be to make a conda package for Seqwish ?

**Comment by ekg** [comment]
I've never made a conda package. I don't know. It shouldn't be any more
complicated than odgi.

**Comment by subwaystation** [comment]
@ekg As mentioned in https://github.com/JervenBolleman/spodgi/issues/3 @apeltzer and @subwaystation will package it in conda ;)

**Comment by SilasK** [comment]
Ok, then we would need a release from Seqwish as well. I can help to make the conda package. Could you ping the PR on bioconda/bioconda for odgi?

**Comment by ekg** [comment]
I've made a seqwish release https://github.com/ekg/seqwish/releases/tag/v0.1

**Comment by SilasK** [comment]
>  As mentioned in JervenBolleman/spodgi#3 @apeltzer and @subwaystation will package it in conda ;)

@apeltzer and @subwaystation have you still intention in doing so?

**Comment by subwaystation** [comment]
I don't know about @apeltzer, but I still have the intention. 
Apparently, a lot of things were alredy tried out. See bioconda/bioconda-recipes#18743. But I do not have any experience with `CMAKE`, so I don't know what to do.
 @ekg Do you have any idea?

**Comment by ekg** [comment]
I've been able to build odgi with guix. Is there a way to work from this
recipe?

https://github.com/ekg/guix-genomics/blob/master/odgi.scm

**Comment by subwaystation** [comment]
@SilasK please take a look at #75 for further updates.
