### ISSUE TITLE
--out flag doesn't work with matrix or bin

### ISSUE THREAD

**Issue by trgibbons** [vgteam/odgi#60]
The `--out` flag worked for me with the `build` subcommand, but not with the `matrix` or `bin` subcommands. Those subcommands wrote the output to stdout, whether or not I specified `--out`.

**Comment by ekg** [comment]
Right, it's not hooked up in these. I should probably remove it. The idea
is that text based outputs can be put to stdout.

**Comment by subwaystation** [comment]
Only stdout is supported. `--out` is not listed anymore as an option for both `matrix` and `bin`.
