### ISSUE TITLE
viz testing of 12 Ath. thaliana genomes

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#74]
Executing the following code on a given Ath. thaliana GFA with 12 genomes a 5 chromosomes I get the following output:
![sebastian Athaliana all 50000 sorted og 1D](https://user-images.githubusercontent.com/10184961/73558224-0d0ab000-4453-11ea-8056-3bfd3a5493d0.png)
```bash
#!/bin/bash
ODGI=~/software/odgi/git/master/bin/odgi
GFA=sebastian.Athaliana.all.50000.gfa
OG=${GFA%.gfa}.og
SOG=${GFA%.gfa}.sorted.og

## Build the sparse matrix form of the gfa graph
echo "### odgi build"
BLDPREF=${0%.sh}_01_build
/usr/bin/time -v -o ${BLDPREF}.time \
ionice -c2 -n7 \
$ODGI build \
--progress \
--gfa=$GFA \
--out=$OG \
> ${BLDPREF}.log 2>&1
#--sort \

## Sort paths by 1D sorting
echo "### odgi sort"
SRTPREF=${0%.sh}_02_sort
/usr/bin/time -v -o ${SRTPREF}.time \
ionice -c2 -n7 \
$ODGI sort \
--pipeline="bSnSnS" \
--sgd-use-paths \
--paths-max \
--progress \
--idx=$OG \
--out=$SOG \
--threads="20"\
> ${SRTPREF}.log 2>&1

~/software/odgi/git/master/bin/odgi viz -i sebastian.Athaliana.all.50000.sorted.og -o sebastian.Athaliana.all.50000.sorted.og.png -x 5000 -y 1000 -P 10
```

**Comment by subwaystation** [comment]
Now using "bnS":
![sebastian Athaliana all 50000 sorted og](https://user-images.githubusercontent.com/10184961/73945521-b68aef00-48f4-11ea-903a-6d356d2cf392.png)

@ekg What do you think? 
Which one do we want to have in our Schematize for testing? @josiahseaman

**Comment by ekg** [comment]
Well, it's much less crazy than the multi-sort one. I'm not sure why repeating it makes it compress things so intensely.

Note that there aren't as many graph-spanning links. There are some regions of consistent association. I'm not sure what to make of that.

It could be OK to view this kind of thing by subsetting to the bins touched by a given reference. The idea would be to make the x axis the ordered bins of a given path, and just that path, removing things outside of it.

I'm curious if the structures that this sort shows are meaningful in a genome evolution sense. Not sure how to figure that out.

**Comment by josiahseaman** [comment]
-bnS is clearly an improvement over the first one.  It's just strange that the top level of organization still seems fragmented.  There's so few top level pieces, I'm tempted to manually reorder them.  Though it's obviously ideal if the program gets the chromosome ordering right by itself.  I'll look at this in Schematize to see how many of those long range links are sitting next to each other.  What is the download or filename for the latest bnS file?

**Comment by subwaystation** [comment]
You can find the binned files on pantograph2 `/home/ubuntu/sh/20_sebastian_odgi_1D_sort_23012020_bSn`. I would go for a bin size of 100000, else we would run into performance issues I guess.

**Comment by subwaystation** [comment]
@ChriKub What do you think of the sortings? You have the most experience with this data.

**Comment by ChriKub** [comment]
bnS is much better. I like it.
I struggle to see the 5 chromosomes that should be visible. This might be an artifact of the graph that was provided. It was build with an older seqwish version and was intended to align as many TE and repetitive regions as possible, probably leading to more fragmentation in the sorting. We should try this with a newer version of the graph.

**Comment by josiahseaman** [comment]
I think non-overalpping paths have been collapsed into the same row.  If you look at the far right and left of the second mega-row, you'll see there's two different sets of colors.  I think those are two chromosomes that didn't overlap so they could be stacked side by side.  I think the top row also has two sets of colors, which would bring the total to 5 distinct sets of colors (chromosomes).

**Comment by ekg** [comment]
Add -R to the odgi viz call to force paths to have their own row.

**Comment by subwaystation** [comment]
Now with "-R". 

`~/software/odgi/git/master/bin/odgi viz -i sebastian.Athaliana.all.50000.sorted.og -o sebastian.Athaliana.all.50000.sorted.og.R.png -x 5000 -y 1000 -P 10 -R`

![sebastian Athaliana all 50000 sorted og R](https://user-images.githubusercontent.com/10184961/74015525-13d47e00-4991-11ea-9a43-77979d74f265.png)

Now I can kind of see the 5 chromosomes, but the huge overlap of `chr2` and `chr3` in the middle is puzzling me.

**Comment by ekg** [comment]
Try running without the -K option for using path based distances.

I need to work on the node pair sampling scheme...

**Comment by ChriKub** [comment]
That looks even better. Without positional information it is hard to judge what is going on there. But I've observed a graph merge of those chromosomes before.
What worries me more is the one path in Chr 4 that completely aligns to Chr1.

**Comment by ekg** [comment]
Maybe I should add an option to plot progress along the paths.

**Comment by subwaystation** [comment]
Without -K.

![sebastian Athaliana all 50000 sorted og R noK](https://user-images.githubusercontent.com/10184961/74021759-6ff0cf80-499c-11ea-84d5-45c471c0dd82.png)

**Comment by ekg** [comment]
Keeping -K, try -p eSn and -p sSn

**Comment by subwaystation** [comment]
-K -p eSN
-R in viz

![sebastian Athaliana all 50000 sorted og R_K_eSn](https://user-images.githubusercontent.com/10184961/74136539-81c9b100-4bee-11ea-8f70-3254e4fbd6a3.png)

**Comment by subwaystation** [comment]
@ekg @josiahseaman @ChriKub I think it looks worse with much more links.

**Comment by ChriKub** [comment]
Yes. The previous vesion was better.

**Comment by subwaystation** [comment]
This is -R
-K -sSN
![sebastian Athaliana all 50000 sorted og R_K_sSn](https://user-images.githubusercontent.com/10184961/74144998-230c3380-4bfe-11ea-9ddd-08de258bba78.png)

So -bnS with -K was the best, as far as I got from @ChriKub .
@ekg You need some more example sortings, or does this suffice for you?

**Comment by ekg** [comment]
bnS looks good. Does it change much when adding an "n" on the end?

`-p bnSn` would be the pattern.

The unseeded toposort really helps make the graph sensible on a smaller
scale. It might be a requirement that it goes last.

**Comment by subwaystation** [comment]
-R
-p bnSn

![sebastian Athaliana all 50000 sorted og R no_K bnSn](https://user-images.githubusercontent.com/10184961/74170181-cecc7800-4c2c-11ea-8c83-07c977e801f9.png)

@ekg @ChriKub What do you think?

Maybe we should wait for the more recent data of @ChriKub ?

**Comment by subwaystation** [comment]
@josiahseaman The path on pg2 is `/mnt/vol1/sh/ath_christian_kubica/20_sebastian_odgi_1D_sort_23012020_bnSn_no_K_R/sebastian.Athaliana.all.50000.w100.json` as you suspected.

**Comment by subwaystation** [comment]
As the data discussed here is not published yet, I am closing this issue.
I will open another one for the new data form @ChriKub.
