### ISSUE TITLE
Bring ODGI to Bioconda

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#75]
We are trying to bring ODGI to Bioconda. The latest problem indicated in bioconda/bioconda-recipes#18743 was that ODGI did not build because of it's `sonLib` dependency.
@ekg mentioned that it is not needed. Therefore, I will remove this dependency.

**Comment by subwaystation** [comment]
@ekg Which python versions does `odgi` support?
I expect no `2.7`?
But from `3.x`?

**Comment by ekg** [comment]
It's only dependent on pybind11. Python3 something. I'm not sure even how
to test.

**Comment by subwaystation** [comment]
We have a build for our current conda branch @SilasK. For instructions please see https://github.com/bioconda/bioconda-recipes/pull/18743#issuecomment-58144562.

**Comment by JervenBolleman** [comment]
No point in trying to support 2.7 python with new code when BioPython etc. are dropping it.

**Comment by subwaystation** [comment]
@ekg How about a release 0.2 after merging of #76? Then we can have a stable `conda` built and correspond the the bioconda rulebook.

**Comment by ekg** [comment]
https://github.com/vgteam/odgi/releases/tag/0.2

**Comment by subwaystation** [comment]
Awesome, thanks!

**Comment by subwaystation** [comment]
Tadaa!
https://anaconda.org/bioconda/odgi
There you go @SilasK.
