### ISSUE TITLE
Show nucleotide position in each bin for each path

### ISSUE THREAD

**Issue by josiahseaman** [vgteam/odgi#78]
In order to really make odgi and dependent visualizations be able to inter-operate with the rest of the Bioinformatics world, we need nucleotide positions for any feature, which will be different for each path.  Here's what I propose:

- [ ] Find code in odgi bin that is generating mean_pos
- [ ] Find the total length of each path
- [ ] Add center_nucleotide to Bin[3]
- [ ] Output center_nucleotide in bin output json
- [ ] Introduce JSON format version number so we can detect data incompatibility in the future

**Comment by ekg** [comment]
Ah I see what could go wrong. We should add the center_position in parallel
so as to not break odgi bin visualization in R.

**Comment by josiahseaman** [comment]
It shall be done as you say.

**Comment by josiahseaman** [comment]
The latest PR is changed to include first_nucleotide and last_nucleotide.  No median.

**Comment by subwaystation** [comment]
Is there still something open here @josiahseaman or can we close this?
