### ISSUE TITLE
odgi build - make -o and --out mandatory arguments

### ISSUE THREAD

**Issue by subwaystation** [vgteam/odgi#90]
`odgi build` runs through with just specifying the input graph. But it does not store it anywhere nor does it print to std::cout. I would suggest to make the `-o / --out` a mandatory argument @ekg ?

**Comment by ekg** [comment]
That's a very good idea. This would apply to many other commands too.

**Comment by subwaystation** [comment]
I hope I will find most of them during documentation. I won't create any more issues regarding mandatory arguments and ship the fixes via #92.
