### ISSUE TITLE
Request for new 0.3 release and bump for Bioconda recipe

### ISSUE THREAD

**Issue by heuermh** [vgteam/odgi#93]
There are command line changes to `odgi` since the 0.2 release tag, the basis for the most recent Bioconda recipe.

Might it be possible to cut a new 0.3 release tag and bump the Bioconda recipe?

```nextflow
    container "heuermh/odgi-dev:latest"
    """
    odgi build -g $graph -o - \
      | odgi prune -i - -b 3 -o - \
      | odgi view -i - -g >${sample}.odgi-prune.b3.gfa
    """

    /*
    container "quay.io/biocontainers/odgi:0.2--py37h8b12597_0"
    """
    odgi build -g $graph -o - \
      | odgi prune -k 16 -i - -o - \
      | odgi view -i - -g >${sample}.odgi-prune.b3.gfa
    """
    */
```

Thank you in advance!

**Comment by subwaystation** [comment]
@heuermh @ekg Made a new release, but apparently the `autobump` of bioconda did not work. I am still seeing 0.2 there.

Maybe @dpryan79 can help us here?

**Comment by heuermh** [comment]
@subwaystation That is great!  If there is a new release, I can do the bump in bioconda manually later today

**Comment by dpryan79** [comment]
The autobump job seems to have missed a number of things lately, not sure why. Thanks for taking care of it manually @heuermh!

**Comment by heuermh** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/21320

**Comment by subwaystation** [comment]
Thanks to @heuermh and @dpryan79  this is solved via https://github.com/bioconda/bioconda-recipes/pull/21320#event-3203992191.
