### ISSUE TITLE
Output "Zoom Stack" list of bin widths

### ISSUE THREAD

**Issue by josiahseaman** [vgteam/odgi#98]
Currently we use a script which invokes odgi bin multiple times with different bin widths.  I believe this should be a single invocation that accepts a list of widths instead.  This particularly becomes relevant in the case where we're outputting sequence (at bin_width=1) and we want to reuse that same sequence file at every bin_width level.  Sequence and bin declarations should be excluded in every bin_width json file because a single FASTA file covers sequence needs for all sizes.  

- [ ] argument accepts list instead of single number
- [ ] internal invocation loop for each bin_width
- [ ] add "fasta_file" key to json header

Currently the script looks like this:
```bash
echo "### odgi bin"
for w in 1 10 100 1000; do
	BIN=${GFA%.gfa}.w${w}.json
	BINPREF=${0%.sh}_04_bin_w${w}
	/usr/bin/time -v -o ${BINPREF}.time \
	ionice -c2 -n7 \
	$ODGI bin \
	--json \
	--idx=$SOG \
	--bin-width=${w} \
	--fasta $FASTA \
	1> $BIN \
	2> ${BINPREF}.log &
done
```
It would change to listing the prefix in $BIN and then automatically appending w${w}.json to the end of each file created.  Since this is one invocation, it would make one .time file.  This may also speed up by eliminating the need to reload the --idx each time?

**Question:** Does this proposal disrupt any features related to the stdout pipe?  Where is that used and is there a multi-file solution that still allows usage of the stdout pipe?

Follow on to #88.

**Comment by josiahseaman** [comment]
An example of my test procedure is here: https://github.com/vgteam/odgi/pull/96#issuecomment-608081718 complete with data file and script.

**Comment by ekg** [comment]
It won't have any utility to make it directly output the whole stack or
not. The runtime is exactly the same, modulo shell invocations and graph
load, which should be minor in all but the largest graphs. Just loop over
the desired bin widths.

**Comment by subwaystation** [comment]
We can always adjust the bash script. For `w=1` we can output the FASTA as a default. We can chat about the organization of all other bin widths.
